version: "3.1"
services:
  mysql:
    image: mariadb:latest 
    container_name: portal_pacientes_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal_paciente_LR
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/portal_paciente_database:/var/lib/mysql
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    # build: .
    image: eamanu/portal_paciente:dev
    container_name: portal_pacientes_app
    env_file:
      - .env_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:8000

  frontend:
    image: eamanu/portal_paciente_frontend:prod
    container_name: portal_pacientes_frontend
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
